# Generated by Django 6.0.1 on 2026-01-17 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('DAMA', 'Dama'), ('HOMBRE', 'Hombre'), ('NINO', 'Niño')], max_length=10, verbose_name='Género')),
                ('tipo_producto', models.CharField(choices=[('CAMISETA', 'Camiseta'), ('SUDADERA', 'Sudadera'), ('PANTALONETA', 'Pantaloneta')], max_length=15, verbose_name='Tipo de producto')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, verbose_name='Talla')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio (COP)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Producto')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size', verbose_name='Talla')),
            ],
            options={
                'verbose_name': 'Stock por talla',
                'verbose_name_plural': 'Stock por talla',
            },
        ),
    ]
