# Generated by Django 6.0.1 on 2026-01-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen principal'),
        ),
    ]
