# Generated by Django 6.0.1 on 2026-01-17 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_imagen_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagen_principal',
        ),
        migrations.AlterField(
            model_name='size',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Talla'),
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('producto', 'talla')},
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='store.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Foto de producto',
                'verbose_name_plural': 'Fotos de producto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
