# Generated by Django 6.0.1 on 2026-01-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_imagen_principal_alter_size_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(default='Betel Casa de Dios', max_length=120, verbose_name='Nombre de la marca')),
                ('ciudad_base', models.CharField(default='Turbo, Antioquía', max_length=120, verbose_name='Ciudad base')),
                ('whatsapp_numero', models.CharField(default='573001099123', max_length=20, verbose_name='WhatsApp (solo números, con indicativo)')),
                ('horario_atencion', models.CharField(default='24/7', max_length=120, verbose_name='Horario de atención')),
                ('dias_produccion', models.CharField(default='3 días', max_length=120, verbose_name='Tiempo de producción')),
                ('envio_tiempo', models.CharField(default='3 a 5 días hábiles (según ciudad)', max_length=120, verbose_name='Tiempo de envío')),
                ('envio_nota', models.TextField(blank=True, default='Envío con transportadora (uso exclusivo).', verbose_name='Nota de envío')),
                ('politicas_no_devolucion', models.TextField(default='No realizamos devoluciones por talla o gusto. Marca 100% online, no contamos con tienda física.', verbose_name='Política (no devoluciones)')),
                ('excepcion_falla', models.TextField(default='Única excepción: falla de estampado. Se reporta máximo 1–2 días después de entregado.', verbose_name='Excepción por falla')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo (opcional)')),
            ],
            options={
                'verbose_name': 'Ajustes del sitio',
                'verbose_name_plural': 'Ajustes del sitio',
            },
        ),
    ]
