# Generated by Django 6.0.1 on 2026-01-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='terminos_html',
            field=models.TextField(blank=True, default='', verbose_name='Términos y condiciones (texto)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='texto_marca',
            field=models.TextField(blank=True, default='', verbose_name='Texto de marca (calidad / edición limitada)'),
        ),
    ]
